# Usa a imagem do Node.js 14 como base
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:14

# Instala Angular CLI 15.0.5
RUN npm install -g @angular/cli@15.0.5

# Define o diretório de trabalho
WORKDIR /workspace
